version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pingpongdb
    volumes:
      - pingpong-db-data:/var/lib/postgresql/data

volumes:
  pingpong-db-data: